### ISSUE TITLE
Clever use of Popups

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Pyroseza/Random#1]
While I was not able to get the tts_form.py file to work, I did get it to run until the credentials failed.

I saw the message that Google was loading and had zero clue at all that the message was going from PySimpleGUI!  I learned something cool!    I have never tried that combination of things.  I'm thinking now of making it a new type of popup.  I don't have any quite like the message only that you implemented.

Have you tried using a No-wait type of popup with the timeout?  This way the execution will continue while the message is being displayed.  I just tested it and it works great.... those 2 seconds while the window is visible will be spent by your application actually loading stuff.  Change the window to PopupNoWait and set auto_close=True.  Or use `PopupQuick` which sets both of these options for you.  The only thing you have to add is the `no_titlebar`.

This past weekend there was a pretty big set of changes that got posted.  You don't have to use RButton anymore.  Buttons now act like the RButtons did.  They no longer close the window.

You can also change your event loop to remove the sleep.   To do this, change the ReadNonBlocking (I'm trying to get rid of this call entirely) and change it to:

`button, values = window.Read(timeout=100)`

This will delay up to 100 ms while waiting for input.  If no input is found, the Read will return with a "timeout'" event as the reason.  This makes for a much more responsive GUI.

I liked seeing this stuff!  Thanks for posting it.

**Comment by Pyroseza** [comment]
Hi @MikeTheWatchGuy, thanks for the feedback :+1: 
I can show you what it is supposed to look like, it will only work properly if you have a valid Google authentication token for their API hence the timeout errors.

I think I did try that popup and there was a reason I did not go for it, it was behaving strangely for me so I made it work this way for now, I will try out your recommendations and see if it behaves the way I want it to.

I'm not 100% finished with this project, I should have it finished by end of next week.

Thanks for the updates :) I will pull them soon and implement the changes.

There is however something else I've been toying with, maybe you can have a look at that for me please... will commit and push it shortly

**Comment by Pyroseza** [comment]
Code changes made and implemented :) thanks @MikeTheWatchGuy 👍
