### ISSUE TITLE
PySimpleGui / Tkinter bug?!

### ISSUE THREAD

**Issue by Pyroseza** [Pyroseza/Random#2]
Hi @MikeTheWatchGuy, here is the bug I mentioned in the other issue, download this: https://github.com/Pyroseza/Random/blob/master/pysimgui_switch_test.py

And use the "Switch" button, after 3 switches it will break.

I have yet to look into the issue but if you know what is going on that would be great.

I'm trying to be able to have multiple windows without actually using multiple windows, instead I just switch the layout of the same window.

**Comment by MikeTheWatchGuy** [comment]
Layouts cannot be "reused".  I moved your layout definitions inside of your while loop and it works great!

Another use I've not seen before.  Most people don't swap around layouts like this.... keep up the great work!

There is an Issue opened regarding re-using layouts but likely something I won't be able to fix... never know however.

**Comment by MikeTheWatchGuy** [comment]
By the way, why the "Sleep"?  

`CloseNonBlocking` has been renamed to `Close`

Finally, Buttons are all RButtons by default, so you'll never need to use ReadButton or RButton again.  It was part of some rather sweeping changes I made over the weekend to support these persistent windows better.

**Comment by Pyroseza** [comment]
Hahaha I think I can think of a few scenarios you don’t know about. I like to fiddle. 

I still need to pull the latest version, I wrote this before you told me about the updates

**Comment by PySimpleGUI** [comment]
Welcome back... nice to see something older closed for a change.

**Comment by Pyroseza** [comment]
Haha yes indeed, cleaning up github, going to look into using this more actively instead of using other repo tools like bitbucket

**Comment by PySimpleGUI** [comment]
It's truly stunning the number and quality of the free tools available now to developers.  I recall spending SO MUCH money in the past setting up engineering groups on basic source code control, then buying a bug tracking system.... all paid for on a per-seat basis.  It's crazy that development software became so inexpensive in a short span of time.  There's a balance every time that happens though as it leaves zero room for competitors.
